server:
  servlet:
    context-path: /pmbok
spring:
  # 设置DB数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sysapl
    url: jdbc:mysql://localhost:3306/pmbok_sys?serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=UTF8
    druid:
      initial-size: 5
      max-active: 10
mybatis-plus:
  # 配置mybatis-plus
  type-aliases-package: com.lding.pmbok.pojo
  configuration:
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto
# 自定义属性名称-跨域情报
cross:
  cross-origins:
    - http://127.0.0.1:5500
    - http://localhost:5500